#version 450

#extension GL_GOOGLE_include_directive : enable
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable


layout (local_size_x = 16, local_size_y = 16) in;
layout (set = 0, binding = 0, rgba32f) uniform image2D resultImage;

layout (push_constant) uniform Contants
{
	float size;
	vec4 color;
} params;


void main()
{	
    vec2 tex_coords = floor(vec2(gl_GlobalInvocationID.xy) / params.size);
    float mask = mod(tex_coords.x + mod(tex_coords.y, 2.0), 2.0);
	imageStore(resultImage,ivec2(gl_GlobalInvocationID.xy) , mask * params.color);
}
